# ğŸ»â€â„ï¸ğŸ´â€â˜ ï¸ Noel's Helm Charts: Curated catalog of Noel's Helm charts.
# Copyright (c) 2024 Noel Towa <cutie@floofy.dev>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

kubeVersion: ">=1.26"
description: "ğŸ»â€â„ï¸ğŸ’ Easy, and flexible image host to share with your friends on Discord, Telegram, and more."
apiVersion: v2

# renovate: image=auguwu/ume
appVersion: "4.0.3"
version: 0.1.0
type: application
home: https://floofy.dev/oss/ume
name: ume
keywords:
  - image-server
  - ume
maintainers:
  - name: Noel Towa
    email: cutie@floofy.dev
    url: https://floofy.dev
annotations:
  charts.noelware.org/licenses: Apache-2.0
  charts.noelware.org/categories: Miscellaneous
dependencies:
  - name: common
    version: 2.26.0
    repository: oci://registry-1.docker.io/bitnamicharts
